spring.application.name=StockPortfolioMonitoringApp

spring.datasource.url=jdbc:mysql://localhost:3306/stockportfoliomonitoringapp_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#minimum 32-character secret
jwt.secret=StockPortfolioMonitoringAppKeyForJWT2026 
jwt.expiration=86400000
#86400000 = 24 hours

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
